services:
  imgpreviewer:
    build:
      dockerfile: Dockerfile
    container_name: imgpreviewer
    environment:
      IMPR_CACHE_SIZE: 5
      IMPR_CACHE_PATH: /cache
      IMPR_REQ_TIMEOUT: 10
      IMPR_PORT: 8888
      IMPR_LOG_LEVEL: debug
    ports:
      - 8888:8888
